### ISSUE TITLE
[Feature] - Add support for the --sovler option.

### ISSUE THREAD

**Issue by swainn** [macro128/pdm-conda#6]
I'd like to use pdm-conda with the libmamba solver (https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community).

This is normally done by installing libmamba and then adding the `--solver libmamba` option to the install command like so:

```bash
conda install -n base conda-libmamba-solver
conda config install --solver libmamba <some-package>
```

I think the ideal would be if the `solver` option could be specified in the `pyproject.toml`:

```toml
[tool.pdm.conda]
runner = "micromamba"
solver = "libmamba"
```
